Begin test suite
  test cases being run: 1
  Begin test case
    test case name: "exception_sections"
    file: "exception_sections.test.cpp"
    line: 3
    Begin test case run
      Begin section
        sections: 1
      Begin section
        sections: 1, 11
      Begin section
        sections: 1, 11, 111
      Begin assertion
        expression: 12ULL == 12ULL
        line: 11
      End assertion
        assertion success: true
        Binary assertion
          first representation: 12ULL
          second representation: 12ULL
          operation: ==
      End section
        sections: 1, 11, 111
        section success: false
      End section
        sections: 1, 11
        section success: false
      End section
        sections: 1
        section success: false
    End test case run
      test assertions ran: 1
      test assertions passed: 1
      test assertions failed: 0
      test case run success: false
      exception type: class std::runtime_error
      exception message: "error section 111"
    Begin test case run
      Begin section
        sections: 1
      Begin section
        sections: 1, 11
      Begin section
        sections: 1, 11, 112
      End section
        sections: 1, 11, 112
        section success: true
      Begin assertion
        expression: 1 == 1
        line: 20
      End assertion
        assertion success: true
        Binary assertion
          first representation: 1
          second representation: 1
          operation: ==
      Begin assertion
        expression: 2 == 2
        line: 29
      End assertion
        assertion success: true
        Binary assertion
          first representation: 2
          second representation: 2
          operation: ==
      End section
        sections: 1, 11
        section success: true
      End section
        sections: 1
        section success: true
    End test case run
      test assertions ran: 2
      test assertions passed: 2
      test assertions failed: 0
      test case run success: true
    Begin test case run
      Begin section
        sections: 1
      Begin section
        sections: 1, 11
      Begin assertion
        expression: 1 == 1
        line: 20
      End assertion
        assertion success: true
        Binary assertion
          first representation: 1
          second representation: 1
          operation: ==
      Begin section
        sections: 1, 11, 113
      Begin assertion
        expression: 'a' == 'a'
        line: 24
      End assertion
        assertion success: true
        Binary assertion
          first representation: 'a'
          second representation: 'a'
          operation: ==
      Begin assertion
        expression: 'a' == 'b'
        line: 26
      End assertion
        assertion success: false
        Binary assertion
          first representation: 'a'
          second representation: 'b'
          operation: ==
      End section
        sections: 1, 11, 113
        section success: false
      End section
        sections: 1, 11
        section success: false
      End section
        sections: 1
        section success: false
    End test case run
      test assertions ran: 3
      test assertions passed: 2
      test assertions failed: 1
      test case run success: false
      exception type: class std::runtime_error
      exception message: "Assertion failed"
    Begin test case run
      Begin section
        sections: 1
      Begin section
        sections: 1, 11
      Begin assertion
        expression: 1 == 1
        line: 20
      End assertion
        assertion success: true
        Binary assertion
          first representation: 1
          second representation: 1
          operation: ==
      Begin assertion
        expression: 2 == 2
        line: 29
      End assertion
        assertion success: true
        Binary assertion
          first representation: 2
          second representation: 2
          operation: ==
      End section
        sections: 1, 11
        section success: true
      End section
        sections: 1
        section success: true
    End test case run
      test assertions ran: 2
      test assertions passed: 2
      test assertions failed: 0
      test case run success: true
    Begin test case run
      Begin section
        sections: 1
      Begin section
        sections: 1, 12
      End section
        sections: 1, 12
        section success: true
      End section
        sections: 1
        section success: true
    End test case run
      test assertions ran: 0
      test assertions passed: 0
      test assertions failed: 0
      test case run success: true
    Begin test case run
      Begin section
        sections: 2
      End section
        sections: 2
        section success: false
    End test case run
      test assertions ran: 0
      test assertions passed: 0
      test assertions failed: 0
      test case run success: false
      exception type: class std::runtime_error
      exception message: "error section 2"
    Begin test case run
    End test case run
      test assertions ran: 0
      test assertions passed: 0
      test assertions failed: 0
      test case run success: true
  End test case
    test assertions ran: 8
    test assertions passed: 7
    test assertions failed: 1
    test case success: false
End test suite
  test cases ran: 1
  test cases passed: 0
  test cases failed: 1
  test assertions ran: 8
  test assertions passed: 7
  test assertions failed: 1
  test suite success: false
